---

- assert:
    that:
      - ansible_distribution == "Debian"
      - ansible_distribution_major_version|int >= 11
      - ansible_distribution_major_version|int <= 12

      - rma_admin_password != none


- name: Update apt cache if needed
  apt: update_cache=yes cache_valid_time=3600

  
- name: Install some generally required/recommmended packages
  apt:
    name:
      # Sometimes not available on minimal systems:
      - man   
      - unzip
      - bash-completion
      # For PostgreSQL management via ansible/python:
      - python3-psycopg2
      # For installing Perl modules without Debian package:
      - cpanminus
      - make
